# Generated by Django 3.1.3 on 2021-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
