# Generated by Django 3.1.3 on 2021-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210131_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
